# -*- coding: utf-8 -*-
# tasks for  ansible-role-tmuxinator
---
- name: Ensure group "rbenvgrp" exists
  group:
    name: rbenvgrp
    state: present

- name: Check groups that user belongs to already
  shell: "groups"
  failed_when: false
  changed_when: false
  check_mode: no
  become: yes
  become_user: "{{bossjones__tmuxinator__user}}"
  register: bossjones__tmuxinator_user_groups

- debug:
    var: bossjones__tmuxinator_user_groups.stdout | replace(" ", ",")


- name: "Add the user {{bossjones__tmuxinator__user}}, appending the group 'rbenvgrp' to the user's groups"
  user:
    name: "{{bossjones__tmuxinator__user}}"
    groups: "rbenvgrp"
    append: yes

- name: change group ownership of rbenv_root dir
  file:
    path: "{{bossjones__tmuxinator__rbenv_root}}"
    recurse: yes
    group: "rbenvgrp"
    owner: "nobody"

- name: mkdir ~/.tmuxinator
  file:
    path: "~{{bossjones__tmuxinator__user}}/.tmuxinator"
    state: "directory"

# - name: change group ownership of rbenv_root dir
#   file:
#     src: files/install_tmuxinator.sh
#     path: "{{bossjones__tmuxinator__user}}/install_tmuxinator.sh"
#     mode: 0755

- name: install script
  template:
      dest: "~{{bossjones__tmuxinator__user}}/install_tmuxinator.sh"
      src: install_tmuxinator.sh
      mode: 0755

- name: tmuxinator zsh.yml
  template:
      dest: "~{{bossjones__tmuxinator__user}}/.tmuxinator/zsh.yml"
      src: zsh.yml
      owner: "{{bossjones__tmuxinator__user}}"
      group: "{{bossjones__tmuxinator__user}}"

- name: Check groups that user belongs to already
  shell: "~{{bossjones__tmuxinator__user}}/install_tmuxinator.sh"
  become: yes
  become_user: "{{bossjones__tmuxinator__user}}"
  register: install_tmuxinator_res

- debug:
    var: install_tmuxinator_res.stdout
