#!/usr/bin/env bash

set -e

_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "IS_CI_ENVIRONMENT" == "true" ]; then
    export CONTAINER_UID=$(ls -lta | awk '{print $3}')
    export CONTAINER_GID=$(ls -lta | awk '{print $4}')
else
    export CONTAINER_UID=$(id -u)
    export CONTAINER_GID=$(id -g)
fi

# export ANSIBLE_ROLES_PATH="/tmp/molecule/app/default/roles:/app/src"
export WHOAMI=$(whoami)
export HOME=$(getent passwd $WHOAMI | cut -d: -f6)

echo "HOME: ${HOME}"

# export _DATE=$(date +%Y%m%d_%H%M%S)

make test
